### ISSUE TITLE
OS related issue

### ISSUE THREAD

**Issue by pascalcaron** [NickstaDB/patch-apk#9]
Hello @NickstaDB,

First of all thank you for such a great tool.

There is a problem running patch-apk in Windows. 

Project tries to run `apktool` but for Windows it is `apktool.bat`

**Comment by AkshayJainG** [comment]
Here is what you can do 
1)Find where apktool is being called in the code
2)Replace it with the apktool.bat with full PATH. That should work

**Comment by NickstaDB** [comment]
Closing this as it's an environment issue.

At least as far back as Windows XP you could run a `.bat` file without providing the extension. Make sure `apktool` is available on the system path and that you can run it by opening a command prompt and typing `apktool`.

**Comment by pascalcaron** [comment]
> Closing this as it's an environment issue.
> 
> At least as far back as Windows XP you could run a `.bat` file without providing the extension. Make sure `apktool` is available on the system path and that you can run it by opening a command prompt and typing `apktool`.

apktool.bat is already on the path. but problem is python cannot run apktool.bat as using apktool command. 
If you try to run **apktool** on command window on Windows it tries to find proper apktool (exe, bat, com etc etc) in PATH enviorment setting. But python just looks for **apktool** without bat exe etc..

I already solved my problem found that cause. But as it won't work in other people Windows computers. Thats the reason I've created an issue..

**Comment by NickstaDB** [comment]
Ah my bad, thanks for clarifying.

I've pushed an update that should fix this. Not sure what your solution was, but simply calling `apktool.bat` instead doesn't appear to be adequate because `apktool.bat` has a dirty hack to execute the `pause` command if the second command-line parameter is `/c`. The net result is that `patch-apk.py` ends up paused with no feedback to the user, unless debug output is enabled, in which case `Press any key to continue...` is displayed to prompt the user.

I've updated the script so it should now run `apktool.bat` under Windows and send a new line to the process to get rid of the `pause` command allowing the process to finish executing.

Let me know if you have any further problems. Cheers.
